### ISSUE TITLE
Workers UX improvement

### ISSUE THREAD

**Issue by queleok** [JacobALundgren/economy-game#29]
When someone runs the game for the first time, all three of the available workers are mining iron. It's not immediately clear what to do to reallocate them for mining other resources, and also this gives some initial skew in favour of iron. Probably it would be more fair to begin with all workers idle

**Comment by JacobALundgren** [comment]
Yeah it's very possible that this'd be an improvement, together with newly produced workers also defaulting to being idle. Maybe the client should also start off on the help screen to give more of an immediate idea of how to interact with the UI (not that the current one is even remotely similar to what a potential v0.1 UI should be in the first place :D )

**Comment by JacobALundgren** [comment]
Together with this maybe also making the zombie player 1 start with one worker on each resource, not that it serves much of a purpose currently other than testing the user interface for multiple players being present.

**Comment by queleok** [comment]
One more small UI suggestion is to add `<>` symbols around the items that could be increased or decreased. So e.g. when there are 3 available workers, and all of them are idle, respective row would look like this: `< 3`; when 2 of the available 3 workers are idle, respective row would look like this: `< 2 >`; when none of the available workers are idle, respective row would look like this: `0 >`. Ideally pressing the arrow left/right button while some decreasable/increasable item is selected should also highlight the respective symbol on that row. Now that I've written all this description it really feels like it deserves a separate case :D

**Comment by JacobALundgren** [comment]
Hm couldn't it be quite reasonable to keep in the same case, under the interpretation of "worker UX"? Separate commits though, surely :D

**Comment by JacobALundgren** [comment]
Is it really appropriate to apply the < > change to Idle though? Since you're never directly interacting with it I would think that just keeping it as a number is better, as the markings for the other lines really speak about how that line interacts with the Idle number

**Comment by queleok** [comment]
Yea, you're absolutely right, it doesn't make much sense for idle, but for the resources it surely does
